# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'CensaSonarQube'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'logistics-fe-uat'
        cliProjectName: 'logistics-fe-uat'
        cliSources: '.'
    - task: SonarQubeAnalyze@5
    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'Manan''s Docker Hub'
    #     repository: 'mananmongia/privatetestrepo'
    #     command: 'buildAndPush'
    #     Dockerfile: 'Dockerfile'
      